config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controller => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dndchars


  root "dndchars#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dndchar.rb
class Dndchar < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dndchars

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dndchars_controller.rb
class DndcharsController < ApplicationController
  before_action :authenticate_user!

  def index
    @dndchars = current_user.dndchars.all.order("created_at DESC")
  end

  def new
    @dndchar = current_user.dndchars.build
  end

  def create
    @dndchar = current_user.dndchars.build(dndchar_params)

    if @dndchar.save
      redirect_to @dndchar
    else
      render 'new'
    end
  end

  def show
    @dndchar = current_user.dndchars.find(params[:id])
  end

  def update
    @dndchar = Dndchar.find(params[:id])
    if @dndchar.update(dndchar_params)
      redirect_to @dndchar
    else
      render 'edit'
    end
  end

  def edit
    @dndchar = Dndchar.find(params[:id])
  end

  def destroy
    @dndchar = Dndchar.find(params[:id])
    @dndchar.destroy

    redirect_to dndchars_path
  end

  private

  def dndchar_params
    params.require(:dndchar).permit(:charname, :charrace, :charclass, :charlevel, :charalign, :charexp, :charfaction, :charstr, :chardex,
                                    :charcon, :charint, :charwis, :charchar, :charsavestr, :charsavedex, :charsaveint, :charsavewis, :charsavecon, :charsavechar, :characro,
                                    :charanimal, :chararcana, :charathletic, :chardeception, :charhistory, :charinsight, :charintim, :charinv, :charmed, :charnature, :charperc,
                                    :charperform, :charpersuasion, :charreligion, :charslight, :charstealth, :charsurvive, :chardescription, :charnotes)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dndchars_helper.rb
module DndcharsHelper
end

app/views/dndchars/_edit_form.html.erb
<!-- Basic Character Info -->
<%= simple_form_for @dndchar do |f| %>
  <section class="section">
    <p class="level-item">
      <strong class="title is-6 is-italic">Basic Character Information</strong>
    </p>
    <hr />
    <div class="columns">
      <div class="column">
        <%= f.input :charname,label: "Name", :placeholder => "Name",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charrace,label: "Race", :placeholder => "Race", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charclass,label: "Class", :placeholder => "Class", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charlevel,label: "Level", :placeholder => "Level", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= f.input :charalign,label: "Alignment", :placeholder => "Alignment",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charfaction,label: "Faction", :placeholder => "Faction", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charexp,label: "Experience Points", :placeholder => "Experience Points", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
  </section>

  <!-- Character Levels -->
  <section class="section">
    <p class="level-item">
      <strong class="title is-6 is-italic">Character Levels</strong>
    </p>
    <hr />
    <div class="columns">
      <div class="column">
        <%= f.input :charstr,label: "Strength", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :chardex,label: "Dexterity", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charcon,label: "Constitution", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= f.input :charint,label: "Intelligence", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charwis,label: "Wisdom", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charchar,label: "Charisma", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
  </section>

  <!-- Saving Throws -->
  <section class="section">
    <p class="level-item">
      <strong class="title is-6 is-italic">Saving Throws</strong>
    </p>
    <hr />
    <div class="columns">
      <div class="column">
        <%= f.input :charsavestr,label: "Strength", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charsavedex,label: "Dexterity", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charsavecon,label: "Constitution", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= f.input :charsaveint,label: "Intelligence", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charsavewis,label: "Wisdom", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charsavechar,label: "Charisma", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
  </section>

  <!-- Character Skills -->
  <section class="section">
    <p class="level-item">
      <strong class="title is-6 is-italic">Character Skills</strong>
    </p>
    <hr />
    <div class="columns">
      <div class="column">
        <%= f.input :characro,label: "Acrobatics", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charanimal,label: "Animal Handling", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :chararcana,label: "Arcana", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charathletic,label: "Athletics", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :chardeception,label: "Deception", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charhistory,label: "History", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= f.input :charinsight,label: "Insight", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charintim,label: "Intimidation", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charinv,label: "Investigaion", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charmed,label: "Medicine", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charnature,label: "Nature", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charperc,label: "Perception", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
    </div>
    <div class="columns is-one-sixth">
      <div class="column">
        <%= f.input :charperform,label: "Perform", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charpersuasion,label: "Persuasion", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charreligion,label: "Religion", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
      <div class="column">
        <%= f.input :charslight,label: "Slight of Hand", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
      <div class="column">
        <%= f.input :charstealth,label: "Stealth", :placeholder => "[1-20]", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charsurvive,label: "Survival", :placeholder => "[1-20]",input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }%>
      </div>
    </div>
  </section>
  <section class="section">
    <p class="level-item">
      <strong class="title is-6 is-italic">Notes & Description</strong>
    </p>
    <hr />
    <div class="columns is-one-half">
      <div class="column">
        <%= f.input :chardescription,label: "Description", :placeholder => "Description goes here", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
      <div class="column">
        <%= f.input :charnotes,label: "Notes", :placeholder => "Notes go here", input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
  </section>
  <%= f.button :submit, 'Edit character', class: "button is-primary" %>
<%end %>

app/views/dndchars/edit.html.erb
<% content_for :page_title, "Edit character" %>

<%= render 'edit_form' %>

app/views/dndchars/index.html.erb
<% content_for :page_title, "Characters" %>

<section class="section">
  <div class="container">
    <% @dndchars.each do |dnd| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"><%= link_to dnd.charname, dnd  %></p>
            </div>
          </div>
          <!--<div class="content">
            level: <%= dnd.charlevel %> race: <%= dnd.charrace %>
          </div> -->
          <div class="columns">
            <div class="column is-one-third">Level: <%= dnd.charlevel %></div>
            <div class="column">Race: <%= dnd.charrace %></div>
            <div class="column">Class: <%= dnd.charclass %></div>
          </div>
          <!--<div class="coment-count">
          <span class="tag is-rounded"><%# #comment count %> </span>
        </div>-->
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/dndchars/new.html.erb
<% content_for :page_title, "Create a new character" %>

<%= render 'form' %>

app/views/dndchars/show.html.erb
<% content_for :page_title, @dndchar.charname %>

<section class="section">
  <div class="container">
   <nav class="level">
     <!-- Left side -->
     <div class="left-side">
       <p class="level-item">
         <strong>Actions</strong>
       </p>
     </div>

     <!-- Right side -->
     <div class="level-right">
       <p class="level-item">
         <%= link_to "Edit", edit_dndchar_path(@dndchar), class: "button" %>
       </p>
       <p class="level-item">
        <%= link_to "Delete", dndchar_path(@dndchar), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
       </p>
     </div>
   </nav>
    <hr />



    <!-- <div class="content">
      Level: <%= @dndchar.charlevel %>
    </div> -->

  </div>
</section>

<!-- Basic Character Info Columns -->
<section class="section">
  <div class="left-side">
    <p class="level-item">
      <strong class="title is-6 is-italic">Basic Character Information</strong>
    </p>
  </div>
  <div class="container">
      <div class="card">
        <div class="card-content">
          <div class="columns">
            <div class="column is-one-third">Level: <%= @dndchar.charlevel %></div>
            <div class="column">Race: <%= @dndchar.charrace %></div>
            <div class="column">Class: <%= @dndchar.charclass %></div>
          </div>
          <div class="columns">
            <div class="column is-one-third">Alignment: <%= @dndchar.charalign %></div>
            <div class="column">Experience Points: <%= @dndchar.charexp %> </div>
            <div class="column">Faction: <%= @dndchar.charfaction %> </div>
          </div>
          <!--<div class="coment-count">
          <span class="tag is-rounded"><%# #comment count %> </span>
        </div>-->
        </div>
      </div>
  </div>
</section>

<!-- Character Levels -->
<section class="section">
  <div class="left-side">
    <p class="level-item">
      <strong class="title is-6 is-italic">Character Levels</strong>
    </p>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-content">
        <div class="columns">
          <div class="column is-one-third">Strength: <%= @dndchar.charstr %></div>
          <div class="column">Dexterity: <%= @dndchar.chardex %></div>
          <div class="column">Constitution: <%= @dndchar.charcon %></div>
        </div>
        <div class="columns">
          <div class="column is-one-third">Intelligence: <%= @dndchar.charint %></div>
          <div class="column">Wisdom: <%= @dndchar.charwis %> </div>
          <div class="column">Charisma: <%= @dndchar.charchar %> </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Character Saving Throws -->
<section class="section">
  <div class="left-side">
    <p class="level-item">
      <strong class="title is-6 is-italic">Saving Throws</strong>
    </p>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-content">
        <div class="columns">
          <div class="column is-one-third">Strength: <%= @dndchar.charsavestr %></div>
          <div class="column">Dexterity: <%= @dndchar.charsavedex %></div>
          <div class="column">Constitution: <%= @dndchar.charsavecon %></div>
        </div>
        <div class="columns">
          <div class="column is-one-third">Intelligence: <%= @dndchar.charsaveint %></div>
          <div class="column">Wisdom: <%= @dndchar.charsavewis %> </div>
          <div class="column">Charisma: <%= @dndchar.charsavechar %> </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Character Skills -->
<section class="section">
  <div class="left-side">
    <p class="level-item">
      <strong class="title is-6 is-italic">Skills</strong>
    </p>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-content">
        <div class="columns">
          <div class="column is-one-sixth">Acrobatics: <%= @dndchar.characro %></div>
          <div class="column">Animal Handling: <%= @dndchar.charanimal %></div>
          <div class="column">Arcana: <%= @dndchar.chararcana %></div>
          <div class="column">Athletics: <%= @dndchar.charathletic %> </div>
          <div class="column">Deception: <%= @dndchar.chardeception %></div>
          <div class="column">History: <%= @dndchar.charhistory %> </div>
        </div>
        <div class="columns">
          <div class="column is-one-sixth">Insight: <%= @dndchar.charinsight %></div>
          <div class="column">Intimidation: <%= @dndchar.charintim %></div>
          <div class="column">Investigation: <%= @dndchar.charinv %></div>
          <div class="column">Medicine: <%= @dndchar.charmed %> </div>
          <div class="column">Nature: <%= @dndchar.charnature %></div>
          <div class="column">Perception: <%= @dndchar.charperc %> </div>
        </div>
        <div class="columns">
          <div class="column is-one-sixth">Performance: <%= @dndchar.charperform %></div>
          <div class="column">Persuasion: <%= @dndchar.charpersuasion %></div>
          <div class="column">Religion: <%= @dndchar.charreligion %></div>
          <div class="column">Sleight of Hand: <%= @dndchar.charslight %> </div>
          <div class="column">Stealth: <%= @dndchar.charstealth %></div>
          <div class="column">Survival: <%= @dndchar.charsurvive %> </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Notes & Description -->
<section class="section">
  <div class="left-side">
    <p class="level-item">
      <strong class="title is-6 is-italic">Notes & Description</strong>
    </p>
  </div>
  <div class="container">
    <div class="card">
      <div class="card-content">
        <div class="columns">
          <div class="column is-one-sixth">Description: <%= @dndchar.chardescription %></div>
          <div class="column">Notes: <%= @dndchar.charnotes %></div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-grey-lighter">
  <head>
    <title>DndLibrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <nav class="navbar is-info">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">DnD Character Library</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbarExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "button is-info" %>
              </p>
             <p class="control">
                <%= link_to "Create New Character", new_dndchar_path, class: "button is-info" %>
             </p>
              <div class="navbar-end">
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
              </div>
            <% else %>
              <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <%= yield %>
  </body>
</html>